Converts markdown to HTML so open in new page works
MolSSI/QCArchiveWebapps pull request #69
Opened 2020-03-12 18:29 UTC by dgasmith

## Description

## Changelog description

## Status
- [x] Ready to go

2020-03-12 18:43 UTC, mattwelborn approved these changes

2020-03-12 18:57 UTC, doaa-altarawy requested changes
Looks good. Just comment out the `qc_time_estimator `app in `app/__init__.py:register_dashapps()`

2020-03-12 22:28 UTC, dgasmith commented
Done, as a note the merge shouldn't have needed this. Please deploy when ready.

2020-03-13 12:52 UTC, doaa-altarawy approved these changes

2020-03-13 12:53 UTC, merged